apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-debugger-deployment
spec:
  selector:
    matchLabels:
      app: k8s-debugger
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-debugger
    spec:
      containers:
        - name: k8s-debugger
          image: mouhamedali/k8s-debugger
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 2
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 2
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-debugger
  name: k8s-debugger-service
spec:
  selector:
    app: k8s-debugger
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080