name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define tag name
        shell: bash
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          TAG_PREFIX=$(echo $GITHUB_REF_NAME | cut -d'-' -f1)
          TAG_NAME=${TAG_PREFIX}-$(date +%Y%m%d%H%M)-$(git rev-parse --short HEAD)
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "tag name is :: $TAG_NAME"

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        # B : for the batch mode
        #  -f,--file : Force the use of an alternate POM file (or directory with pom.xml)

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # This docker tag will be shown as an environment variable in our container
          build-args: |
            "DOCKER_TAG=${{ env.TAG_NAME }}"
          # Note: tags has to be all lower-case
          tags: |
            mamdouni/k8s-debugger:latest
            mamdouni/k8s-debugger:${{ env.TAG_NAME }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}