name: Push an Helm Release on GCR

permissions:
  packages: write
  contents: read

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./charts/k8sdebugger

jobs:

  push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "CHART_NAME=$(cat Chart.yaml | grep 'name' | awk '{printf $2}')" >> $GITHUB_ENV
          echo "CHART_VERSION=$(cat Chart.yaml | grep 'version' | awk '{printf $2}')" >> $GITHUB_ENV

      - name: Show env
        run: |
          echo "CHART_NAME=$CHART_NAME"
          echo "CHART_VERSION=$CHART_VERSION"

      - name: helm lint
        run: |
          helm lint .
      # https://helm.sh/docs/helm/helm_lint/

      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      # https://helm.sh/docs/helm/helm_package/

      - name: helm package
        run: |
          helm package .
      # https://helm.sh/docs/helm/helm_package/

      - name: helm push
        run: |
          helm push $CHART_NAME-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}
      # https://helm.sh/docs/helm/helm_push/
